package com.example.di_ejercicio_lazycolumn_scaffold

fun getJuegos(plataforma: String): List<Juego> {
    var lista = mutableListOf<Juego>(
        Juego("Moster Hunter Rise", "Nintendo Switch", R.drawable.nintendo_monsterhunterrise),
        Juego("FC 24", "XBox Series", R.drawable.xbox_fc24),
        Juego("Bayonetta 3", "Nintendo Switch", R.drawable.nintendo_bayonetta3),
        Juego("Jurassic World Evolution 2", "XBox Series", R.drawable.xbox_jurassicworldevo2),
        Juego("Capitan Tsubasa", "Nintendo Switch", R.drawable.nintendo_captainstsubasa),
        Juego("Resident Evil 4 remake", "XBox Series", R.drawable.xbox_residentevil4),
        Juego("Mario + Rabbids", "Nintendo Switch", R.drawable.nintendo_mariorabbids),
        Juego("PGA 2k23", "PlayStation 5", R.drawable.playstation_pga2k23),
        Juego("NBA 2k23", "PlayStation 5", R.drawable.playstation_nba2k23),
        Juego("Bayonetta 2", "Nintendo Switch", R.drawable.nintendo_bayonetta2),
        Juego("God Of War: Ragnarok", "PlayStation 5", R.drawable.playstation_gowragnarok),
        Juego("FarCry 6", "XBox Series", R.drawable.xbox_farcry6),
        Juego("Kindom magestic", "Nintendo Switch", R.drawable.nintendo_kindommagestic),
        Juego("Crusader kings 3", "PlayStation 5", R.drawable.playstation_crusaderkings3),
        Juego("Stray", "PlayStation 5", R.drawable.playstation_stray),
        Juego("Bayonetta 2", "Nintendo Switch", R.drawable.nintendo_bayonetta2),
        Juego("NBA 2k23", "XBox Series", R.drawable.xbox_nba2k23),
        Juego("Dying Light 2", "XBox Series", R.drawable.xbox_dyinglight2),
        Juego(
            "Horizon: Call of the mountain",
            "PlayStation 5",
            R.drawable.playstation_horizonmontain
        ),
        Juego("Two Point Campus", "PlayStation 5", R.drawable.playstation_2pointcampus),
        Juego("God Of War: Ragnarok", "PlayStation 5", R.drawable.playstation_gowragnarok),
        Juego("Minecraft Legend", "PlayStation 5", R.drawable.playstation_minecraftlegends),
        Juego("Crusader Kings 3", "XBox Series", R.drawable.xbox_crusader_kings3),
        Juego("Mario Strinke", "Nintendo Switch", R.drawable.nintendo_mariostrike),
        Juego("Fifa 23", "PlayStation 5", R.drawable.playstation_fifa23),
        Juego("Riders Republic", "XBox Series", R.drawable.xbox_ridersrepublic),
        Juego("Pikmin 4", "Nintendo Switch", R.drawable.nintendo_pikmin4),
        Juego("Mario Tennis", "Nintendo Switch", R.drawable.nintendo_maritennis),
        Juego("Fifa 23", "PlayStation 5", R.drawable.playstation_fifa23),
        Juego("Age of empire 2", "XBox Series", R.drawable.xbox_ageofempire2),
        Juego("FarCry 6", "XBox Series", R.drawable.xbox_farcry6),
        Juego("NBA 2k23", "PlayStation 5", R.drawable.playstation_nba2k23),
        Juego("Minecraft Legend", "PlayStation 5", R.drawable.playstation_minecraftlegends),
        Juego("Pikmin 4", "Nintendo Switch", R.drawable.nintendo_pikmin4),
        Juego("Stray", "PlayStation 5", R.drawable.playstation_stray),
        Juego("Bayonetta 3", "Nintendo Switch", R.drawable.nintendo_bayonetta3),
        Juego("Capitan Tsubasa", "Nintendo Switch", R.drawable.nintendo_captainstsubasa),
        Juego("Dying Light 2", "XBox Series", R.drawable.xbox_dyinglight2),
        Juego("Jurassic World Evolution 2", "XBox Series", R.drawable.xbox_jurassicworldevo2),
        Juego("PGA 2k23", "PlayStation 5", R.drawable.playstation_pga2k23),
        Juego("Crusader Kings 3", "PlayStation 5", R.drawable.playstation_crusaderkings3),
        Juego("Riders Republic", "XBox Series", R.drawable.xbox_ridersrepublic),
        Juego("Crusader Kings 3", "PlayStation 5", R.drawable.playstation_crusaderkings3),
        Juego("God Of War: Ragnarok", "PlayStation 5", R.drawable.playstation_gowragnarok),
        Juego("Age of empire 2", "XBox Series", R.drawable.xbox_ageofempire2),
        Juego("Fifa 23", "PlayStation 5", R.drawable.playstation_fifa23),
        Juego("Two Point Campus", "PlayStation 5", R.drawable.playstation_2pointcampus),
        Juego("FarCry 6", "XBox Series", R.drawable.xbox_farcry6),
        Juego("NBA 2k23", "PlayStation 5", R.drawable.playstation_nba2k23),
        Juego("Minecraft Legend", "PlayStation 5", R.drawable.playstation_minecraftlegends),
        Juego("Mario Tennis", "Nintendo Switch", R.drawable.nintendo_maritennis),
        Juego("Pikmin 4", "Nintendo Switch", R.drawable.nintendo_pikmin4),
        Juego("Stray", "PlayStation 5", R.drawable.playstation_stray),
        Juego("Bayonetta 3", "Nintendo Switch", R.drawable.nintendo_bayonetta3),
        Juego("Capitan Tsubasa", "Nintendo Switch", R.drawable.nintendo_captainstsubasa),
        Juego("Dying Light 2", "XBox Series", R.drawable.xbox_dyinglight2),
        Juego("FarCry 6", "XBox Series", R.drawable.xbox_farcry6),
        Juego("Jurassic World Evolution 2", "XBox Series", R.drawable.xbox_jurassicworldevo2),
        Juego("NBA 2k23", "XBox Series", R.drawable.xbox_nba2k23),
        Juego("PGA 2k23", "PlayStation 5", R.drawable.playstation_pga2k23),
        Juego(
            "Horizon: Call of the mountain",
            "PlayStation 5",
            R.drawable.playstation_horizonmontain
        ),
        Juego("Crusader kings 3", "XBox Series", R.drawable.xbox_crusader_kings3),
        Juego("Riders Republic", "XBox Series", R.drawable.xbox_ridersrepublic),
        Juego("Bayonetta 2", "Nintendo Switch", R.drawable.nintendo_bayonetta2),
        Juego("Kindom magestic", "Nintendo Switch", R.drawable.nintendo_kindommagestic),
        Juego("Mario + Rabbids", "Nintendo Switch", R.drawable.nintendo_mariorabbids),
        Juego("Mario Strinke", "Nintendo Switch", R.drawable.nintendo_mariostrike),
        Juego("Moster Hunter Rise", "Nintendo Switch", R.drawable.nintendo_monsterhunterrise),
        Juego("Pikmin 4", "Nintendo Switch", R.drawable.nintendo_pikmin4),
        Juego("Mario Tennis", "Nintendo Switch", R.drawable.nintendo_maritennis),
        Juego("Bayonetta 3", "Nintendo Switch", R.drawable.nintendo_bayonetta3),
        Juego("Bayonetta 2", "Nintendo Switch", R.drawable.nintendo_bayonetta2),
        Juego("Kindom magestic", "Nintendo Switch", R.drawable.nintendo_kindommagestic),
        Juego("Capitan Tsubasa", "Nintendo Switch", R.drawable.nintendo_captainstsubasa),
        Juego("Fifa 23", "PlayStation 5", R.drawable.playstation_fifa23),
        Juego("God Of War: Ragnarok", "PlayStation 5", R.drawable.playstation_gowragnarok),
        Juego("Moster Hunter Rise", "Nintendo Switch", R.drawable.nintendo_monsterhunterrise),
        Juego("Pikmin 4", "Nintendo Switch", R.drawable.nintendo_pikmin4),
        Juego("Mario Tennis", "Nintendo Switch", R.drawable.nintendo_maritennis),
        Juego("Bayonetta 2", "Nintendo Switch", R.drawable.nintendo_bayonetta2),
        Juego("Mario Strinke", "Nintendo Switch", R.drawable.nintendo_mariostrike),
        Juego("Fifa 23", "PlayStation 5", R.drawable.playstation_fifa23),
        Juego("God Of War: Ragnarok", "PlayStation 5", R.drawable.playstation_gowragnarok),
        Juego("Minecraft Legend", "PlayStation 5", R.drawable.playstation_minecraftlegends),
        Juego("Crusader kings 3", "PlayStation 5", R.drawable.playstation_crusaderkings3),
        Juego("Riders Republic", "XBox Series", R.drawable.xbox_ridersrepublic),
        Juego("Crusader Kings 3", "PlayStation 5", R.drawable.playstation_crusaderkings3),
        Juego("God Of War: Ragnarok", "PlayStation 5", R.drawable.playstation_gowragnarok),
        Juego("Age of empire 2", "XBox Series", R.drawable.xbox_ageofempire2),
        Juego("Fifa 23", "PlayStation 5", R.drawable.playstation_fifa23),
        Juego("Two Point Campus", "PlayStation 5", R.drawable.playstation_2pointcampus),
        Juego("FarCry 6", "XBox Series", R.drawable.xbox_farcry6),
        Juego("NBA 2k23", "PlayStation 5", R.drawable.playstation_nba2k23),
        Juego("Capitan Tsubasa", "Nintendo Switch", R.drawable.nintendo_captainstsubasa),
        Juego("Minecraft Legend", "PlayStation 5", R.drawable.playstation_minecraftlegends),
        Juego("Pikmin 4", "Nintendo Switch", R.drawable.nintendo_pikmin4),
        Juego("Stray", "PlayStation 5", R.drawable.playstation_stray),
        Juego("Bayonetta 3", "Nintendo Switch", R.drawable.nintendo_bayonetta3),
        Juego("Dying Light 2", "XBox Series", R.drawable.xbox_dyinglight2),
        Juego("Mario Tennis", "Nintendo Switch", R.drawable.nintendo_maritennis),
        Juego("FarCry 6", "XBox Series", R.drawable.xbox_farcry6)
    )
    if (!plataforma.equals("Todas")) {
        lista.removeIf { juego -> juego.plataforma != plataforma }
    }

    return lista;
}